id: A6B66C466
base_file: f3EA5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:11:23.972790
  last_modified_at: 2022-06-15 20:11:23.972798
